server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wujinduo-812/springcloud-config.git
          search-paths:
            - springcloud-config
          force-pull: true
          username: 1273648478@qq.com
          password: Wu19981002
      label: master
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka


